release: 0.6.87

diff --git a/.github/workflows/fairground.yml b/.github/workflows/fairground.yml
--- a/.github/workflows/fairground.yml
+++ b/.github/workflows/fairground.yml
@@ -45,6 +45,7 @@ jobs:
 
     env:
       DEVELOPER_DIR: /Applications/Xcode_13.0_beta.app/Contents/Developer
+      ZERO_AR_DATE: 1
 
     steps:
 
@@ -71,12 +72,6 @@ jobs:
         with:
           fetch-depth: 0
           ref: ${{ github.ref }}
-
-      - name: "Check App Fair Catalog"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          xcrun swift run -- fairtool catalog --verbose true --hub github.com/appfair --token "${{ secrets.GITHUB_TOKEN }}" -o -
 
       - name: "Check releases"
         env:
@@ -195,6 +190,9 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           echo "Creating release: ${GITHUB_REF#refs/tags/}"
+          # if the release already exists, clobber it
+          gh release delete "${GITHUB_REF#refs/tags/}" -y || true
+          # initiate a new release with the tag name
           gh release create \
             "${GITHUB_REF#refs/tags/}" \
             -- \
@@ -215,6 +213,7 @@ jobs:
     timeout-minutes: 45
     env:
       DEVELOPER_DIR: /Applications/Xcode_13.0_beta.app/Contents/Developer
+      ZERO_AR_DATE: 1
 
     steps:
       - name: "Initialize fair-ground"
@@ -261,7 +260,33 @@ jobs:
         run: echo ::set-output name=app_version::$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' ReleasePR/Info.plist)
 
       - name: "Validate App-Name: ${{ env.ORGNAME }}"
-        run: xcrun swift run -- fairtool validate --verbose true --hub github.com/appfair --org "${{ env.ORGNAME }}" --ref "${{ env.COMMITHASH }}" --integrationTitle "${{ env.PRTITLE }}" --maxsize $[1 * 1024 * 1024] --allow-from '.*.EDU' --allow-from '.*.appfair.net' --token "${{ secrets.GITHUB_TOKEN }}" --project ReleasePR --output -
+        run: |
+          xcrun swift run -- fairtool validate \
+            --project ReleasePR \
+            --hub github.com/appfair \
+            --token "${{ secrets.GITHUB_TOKEN }}" \
+            --org "${{ env.ORGNAME }}" \
+            --ref "${{ env.COMMITHASH }}" \
+            --maxsize $[100 * 1024 * 1024] \
+            --integrationTitle "${{ env.PRTITLE }}" \
+            --allow-license "GNU Affero General Public License" \
+            --allow-from '.*@appfair.net' \
+            --allow-from '.*@bc.edu' \
+            --allow-from '.*@berkeley.edu' \
+            --allow-from '.*@caltech.edu' \
+            --allow-from '.*@cornell.edu' \
+            --allow-from '.*@cmu.edu' \
+            --allow-from '.*@harvard.edu' \
+            --allow-from '.*@illinois.edu' \
+            --allow-from '.*@mit.edu' \
+            --allow-from '.*@princeton.edu' \
+            --allow-from '.*@rit.edu' \
+            --allow-from '.*@stanford.edu' \
+            --allow-from '.*@ucla.edu' \
+            --allow-from '.*@washington.edu' \
+            --allow-from '.*@yale.edu' \
+            --verbose true \
+            --output -
 
       - name: Integrate PR
         if: startsWith(steps.get_commit_message.outputs.commit_message, 'release')
@@ -284,6 +309,27 @@ jobs:
           cp -a .build/checkouts Dependencies
           tar cvzf "staging/${{ env.FAIR_APP_ARTIFACT }}-source.tgz" --exclude='.git/' --exclude='.build/' --exclude='staging/' .
           rm -rf Dependencies
+
+      - name: "Build iOS App: ${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa"
+        # there's no way to export iOS archives without re-signing with a teamID, 
+        # so just build the .ipa manually; it needs to be in Staging/ first
+        run: |
+          xcodebuild archive \
+            -workspace "App.xcworkspace" \
+            -configuration Release \
+            -scheme "AppFairApp" \
+            -sdk "iphoneos" \
+            -archivePath "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.xcarchive" \
+            CODE_SIGNING_REQUIRED=NO \
+            CODE_SIGNING_ALLOWED=NO \
+            AD_HOC_CODE_SIGNING_ALLOWED=YES \
+            CODE_SIGN_IDENTITY="-" \
+            PRODUCT_BUNDLE_IDENTIFIER="${{ env.BUNDLE_ID }}" \
+            FAIRAPP_PRODUCT_NAME="${{ env.PRODUCT_NAME }}"
+          cp -a "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.xcarchive/Products/Applications" "staging/Payload"
+          ditto -c -k --sequesterRsrc --keepParent "staging/Payload" "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa"
+          rm -rf "staging/Payload" # cleanup
+          ls -la "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa"
 
       - name: "Build macOS App: ${{ env.FAIR_APP_ARTIFACT }}-macOS.zip"
         run: |
@@ -320,27 +366,6 @@ jobs:
           openssl sha256 "staging/${{ env.PRODUCT_NAME }}.app/Contents/MacOS/"*
           openssl sha256 "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip"
 
-      - name: "Build iOS App: ${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa"
-        # there's no way to export iOS archives without re-signing with a teamID, 
-        # so just build the .ipa manually; it needs to be in Staging/ first
-        run: |
-          xcodebuild archive \
-            -workspace "App.xcworkspace" \
-            -configuration Release \
-            -scheme "AppFairApp" \
-            -sdk "iphoneos" \
-            -archivePath "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.xcarchive" \
-            CODE_SIGNING_REQUIRED=NO \
-            CODE_SIGNING_ALLOWED=NO \
-            AD_HOC_CODE_SIGNING_ALLOWED=YES \
-            CODE_SIGN_IDENTITY="-" \
-            PRODUCT_BUNDLE_IDENTIFIER="${{ env.BUNDLE_ID }}" \
-            FAIRAPP_PRODUCT_NAME="${{ env.PRODUCT_NAME }}"
-          cp -a "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.xcarchive/Products/Applications" "staging/Payload"
-          ditto -c -k --sequesterRsrc --keepParent "staging/Payload" "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa"
-          rm -rf "staging/Payload" # cleanup
-          ls -la "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa"
-
 
       - name: Stage Release Metadata
         # Extract the Info.plist from the archives themselves, since they contain
@@ -352,12 +377,9 @@ jobs:
           plutil -convert xml1 -r -o "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.plist" -- "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.xcarchive/Products/Applications/${{ env.PRODUCT_NAME }}.app/Info.plist"
           find "staging/" -type f
 
-
-      - name: "Upload Build Artifacts"
-        # upload the trusted artifacts for each build for future scrutiny
-        uses: actions/upload-artifact@v2
-        with:
-          path: staging
+      - name: "Install reproducible-builds.org diffoscope"
+        run: |
+          brew install diffoscope || true # in case it is already installed
 
       # compare the contents of the PR's un-trusted artifacts with
       # the contents of the base fair-ground's trusted artifacts
@@ -375,7 +397,20 @@ jobs:
           # client apps will use this hash to verify that the untrusted
           # release artifact that is downloaded matches the release
           # artifact that was created in the trusted environment
-          xcrun swift run -- fairtool fairseal --verbose true --hub github.com/appfair --org "${{ env.ORGNAME }}" --ref "${{ env.COMMITHASH }}" --trusted-artifact "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip" --fairseal-match 50000 --retry-duration 600 --artifact-url "$ZIPURL" --project . -o -
+          xcrun swift run -- fairtool fairseal \
+            --verbose true \
+            --hub github.com/appfair \
+            --org "${{ env.ORGNAME }}" \
+            --ref "${{ env.COMMITHASH }}" \
+            --trusted-artifact "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip" \
+            --fairseal-match 0 \
+            --retry-duration 600 \
+            --artifact-url "$ZIPURL" \
+            --project . -o -
+
+          # also run diffoscope to see what it says about the differences
+          curl -o /tmp/checkartifact.zip "$ZIPURL"
+          diffoscope --html staging/diffoscope-macOS.html /tmp/checkartifact.zip "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip" || true # tolerate changes while developing reproducible builds
 
       - name: "Generate iOS fairseal"
         env:
@@ -388,7 +423,27 @@ jobs:
           echo "Generating fairseal for: $IPAURL"
 
           # Reproducable builds on iOS not yet working
-          xcrun swift run -- fairtool fairseal --verbose true --hub github.com/appfair --org "${{ env.ORGNAME }}" --ref "${{ env.COMMITHASH }}" --trusted-artifact "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa" --fairseal-match 1000000 --retry-duration 600 --artifact-url "$IPAURL" --project . -o -
+          xcrun swift run -- fairtool fairseal \
+            --verbose true \
+            --hub github.com/appfair \
+            --org "${{ env.ORGNAME }}" \
+            --ref "${{ env.COMMITHASH }}" \
+            --trusted-artifact "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa" \
+            --fairseal-match 1000000 \
+            --retry-duration 600 \
+            --artifact-url "$IPAURL" \
+            --project . -o -
+
+          # also run diffoscope to see what it says about the differences
+          curl -o /tmp/checkartifact.ipa "$IPAURL"
+          diffoscope --html staging/diffoscope-iOS.html /tmp/checkartifact.ipa "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa" || true # tolerate changes while developing reproducible builds
+
+      - name: "Upload Build Artifacts"
+        # upload the trusted artifacts for each build for reproducible-builds
+        uses: actions/upload-artifact@v2
+        if: always()
+        with:
+          path: staging
 
       - name: "Publish App Fair Catalog"
         env:
@@ -396,4 +451,5 @@ jobs:
         run: |
           # https://github.com/appfair/appfair.github.io/actions
           gh workflow --repo appfair/appfair.github.io run "catalog.yml"
+
 
